#!/usr/bin/env python3
"""Generate raw Pkl tool requirement objects from generator tools."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATOR_SRC = REPO_ROOT / "generator" / "src"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "generated_tool_config.pkl"

if str(GENERATOR_SRC) not in sys.path:
    sys.path.insert(0, str(GENERATOR_SRC))

from erp_trace_executor.registry import build_default_registry  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output.write_text(render_pkl(), encoding="utf-8")
    return 0


def render_pkl() -> str:
    registry = build_default_registry()
    lines = [
        "// @generated by configuration/generate_tool_config.py",
        "// Contains raw facts read from generator tools. Process logic belongs in Pkl.",
        "",
        'import "objects.pkl"',
        "",
        "toolRequirements: Mapping<String, objects.ToolRequirement> = new Mapping {",
    ]
    for tool_name in sorted(registry.names()):
        spec = registry.get(tool_name)
        schema = spec.input_model.model_json_schema()
        required_fields = tuple(schema.get("required", ()))
        properties = schema.get("properties", {})
        lines.extend(
            [
                f'  ["{_escape(tool_name)}"] = new objects.ToolRequirement {{',
                f'    toolName = "{_escape(tool_name)}"',
                f'    title = "{_escape(_title_from_tool_name(tool_name))}"',
                f'    inputModel = "{_escape(spec.input_model.__name__)}"',
                "    requiredInputFields {",
            ]
        )
        lines.extend(f'      "{_escape(field)}"' for field in required_fields)
        lines.extend(["    }", "    inputProperties {"])
        for name, property_schema in properties.items():
            lines.extend(_render_input_property(name, property_schema, name in required_fields))
        lines.extend(["    }", "  }"])
    lines.extend(["}", ""])
    return "\n".join(lines)


def _render_input_property(name: str, schema: dict[str, Any], required: bool) -> list[str]:
    return [
        "      new objects.ToolInputProperty {",
        f'        name = "{_escape(name)}"',
        f'        schemaType = "{_escape(_schema_type(schema))}"',
        f"        required = {str(required).lower()}",
        f"        defaultValue = {_pkl_optional_string(_default_value(schema))}",
        "      }",
    ]


def _title_from_tool_name(tool_name: str) -> str:
    short_name = tool_name.rsplit(".", maxsplit=1)[-1]
    return short_name.replace("_", " ").title()


def _schema_type(schema: dict[str, Any]) -> str:
    if "type" in schema:
        return str(schema["type"])
    if "anyOf" in schema:
        return " | ".join(_schema_type(item) for item in schema["anyOf"])
    return "unknown"


def _default_value(schema: dict[str, Any]) -> str | None:
    if "default" not in schema:
        return None
    if schema["default"] is None:
        return None
    return str(schema["default"])


def _pkl_optional_string(value: str | None) -> str:
    if value is None:
        return "null"
    return f'"{_escape(value)}"'


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


if __name__ == "__main__":
    raise SystemExit(main())
